### ISSUE TITLE
Enhancement Request : Binder asRequired(Validator method)

### ISSUE THREAD

**Issue by vaithu** [holon-platform/holon-vaadin-flow#104]
I see there are methods for ValidatableInput for validation but there is no option like 
```
binder.forField(emailField).asRequired(new VisibilityEmailValidator("Value is not a valid email address"))
```
Please add something to achieve similar when possible

**Comment by axholo** [comment]
You can already use a custom validator:
`ValidatableInput<String> input = Input.string().validatable().required(new VisibilityEmailValidator("Value is not a valid email address")).build();`
The `VisibilityEmailValidator ` class has to implement `com.holonplatform.core.Validator` interface, e.g.:
```
private class VisibilityEmailValidator implements Validator<String> {

		private final String message;
		
		public VisibilityEmailValidator(String message) {
			super();
			this.message = message;
		}
		
		@Override
		public void validate(String value) throws ValidationException {
			if (/* Validation logic fails*/) {
				throw new ValidationException(message);
			}
		}
		
	}
```
Or using a lambda, e.g:
`ValidatableInput<String> input3 = Input.string().validatable().required(Validator.create(value -> value != null, "My message")).build();`
