### ISSUE TITLE
What's new in 5.5.0?

### ISSUE THREAD

**Issue by vaithu** [holon-platform/holon-vaadin-flow#118]
Can you please put-up some information on What's new in v5.5.0 in vaadin flow? 

I just looked into the updated document but facing difficulty to identify the new concepts/features.

**Comment by axholo** [comment]
List of enhancements and closed issues is in tag description:
https://github.com/holon-platform/holon-vaadin-flow/releases/tag/5.5.0
Milestone:
https://github.com/holon-platform/holon-vaadin-flow/milestone/19?closed=1
