### ISSUE TITLE
ItemListing filtering works only for Datasource

### ISSUE THREAD

**Issue by vaithu** [holon-platform/holon-vaadin-flow#93]
From the below code
dataProvider  = new ListDataProvider<>(new BackendService().getEmployees());
        searchTextField = new TextField(event -> search());
        searchTextField.setSizeFull();
        searchTextField.setValueChangeMode(ValueChangeMode.EAGER);
        add(searchTextField);
        Grid<Employee> employeeGrid = new Grid<>(Employee.class,true);
        employeeGrid.setDataProvider(dataProvider);

private void search() {
        dataProvider.addFilter(employee -> {
            return StringUtils.containsIgnoreCase(employee.getFirstname(),searchTextField.getValue())

                    || StringUtils.containsIgnoreCase(employee.getLastname(),searchTextField.getValue())

                    ;
        });

the dataProvider allows to addFilter for any Bean classes. in Holon-Platform I was trying to find same but ItemListing ( both PropertyListing & BeanListing) always looking for a dataSource aka table to have filtering. 

Without a table, just for simple plain Employee Bean, how to make the filtering like above?

**Comment by axholo** [comment]
You can use Vaadin `DataProvider` with `PropertyListing`/`BeanListing` just in the same way (see [documentation](https://docs.holon-platform.com/current/reference/holon-vaadin-flow.html#ItemListingDataSource)).

If you have a bean as data representation, your example can be written as follows:

```java
ListDataProvider<Employee> dataProvider = new ListDataProvider<>(new BackendService().getEmployees());
		
TextField searchTextField = new TextField();
add(searchTextField);
		
dataProvider.addFilter(employee -> {
    return StringUtils.containsIgnoreCase(employee.getFirstname(), searchTextField.getValue()) ||  StringUtils.containsIgnoreCase(employee.getLastname(), searchTextField.getValue());
});
		
BeanListing<Employee> listing = Components.listing.items(Employee.class)
    .dataSource(dataProvider) // set the DataProvider as data source
    .fullWidth().build();
add(listing.getComponent());
		
searchTextField.setValueChangeMode(ValueChangeMode.EAGER);
searchTextField.addValueChangeListener(event -> listing.refresh()); // (*)
```
(*) Just call `refresh()` on listing API to ensure data is refreshed when filter changes.
